/* Crossover Shelf — AI-assisted Add a Book form
 * Uses the existing browser-local Gemini API key. AI fills the form only; it never saves a book automatically.
 */
(() => {
  "use strict";
  const STORAGE_KEY="crossoverShelfAISettings", DEFAULT_MODEL="gemini-3.6-flash", API_ROOT="https://generativelanguage.googleapis.com/v1beta/models/";
  const STYLE_ID="cs-add-ai-style", BUTTON_ID="cs-add-ai-fill", STATUS_ID="cs-add-ai-status";
  const field=id=>document.getElementById(id), modal=()=>field("bookFormModalBackdrop"), titleInput=()=>field("f-title");
  const loadSettings=()=>{try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}");return{apiKey:s.apiKey||"",model:s.model||DEFAULT_MODEL}}catch(_){return{apiKey:"",model:DEFAULT_MODEL}}};
  function installStyle(){if(field(STYLE_ID))return;const s=document.createElement("style");s.id=STYLE_ID;s.textContent=`.cs-add-ai-wrap{grid-column:1/-1;margin:-2px 0 2px;padding:11px 12px;border:1px solid var(--brass,#caa049);border-radius:10px;background:var(--brass-glow,rgba(202,160,73,.14))}.cs-add-ai-row{display:flex;align-items:center;gap:9px;flex-wrap:wrap}#${BUTTON_ID}{border:1px solid var(--brass,#caa049);background:var(--brass,#caa049);color:var(--ink,#12151d);border-radius:8px;padding:9px 13px;min-height:40px;font-weight:700;cursor:pointer}#${BUTTON_ID}:disabled{opacity:.65;cursor:wait}.cs-add-ai-help{font-size:.72rem;color:var(--text-dim,#8b93a6);line-height:1.45;flex:1;min-width:190px}#${STATUS_ID}{margin-top:7px;font-size:.72rem;line-height:1.4;color:var(--text-dim,#8b93a6);display:none}#${STATUS_ID}.show{display:block}#${STATUS_ID}.error{color:var(--crimson,#b8535c)}.cs-ai-filled{border-color:var(--brass,#caa049)!important;box-shadow:0 0 0 1px rgba(202,160,73,.12)}`;document.head.appendChild(s)}
  function setStatus(m,e=false){const el=field(STATUS_ID);if(!el)return;el.textContent=m||"";el.classList.toggle("show",!!m);el.classList.toggle("error",!!e)}
  function setValue(id,v){const el=field(id);if(!el||v===undefined||v===null||v==="")return false;el.value=String(v);el.classList.add("cs-ai-filled");el.dispatchEvent(new Event("input",{bubbles:true}));el.dispatchEvent(new Event("change",{bubbles:true}));return true}
  function clamp(v,a,b){const n=Number(v);return Number.isFinite(n)?Math.max(a,Math.min(b,n)):null}
  function ensureUI(){const body=modal()?.querySelector(".modal-body"),title=titleInput();if(!body||!title||field(BUTTON_ID))return;installStyle();const w=document.createElement("div");w.className="cs-add-ai-wrap";w.innerHTML=`<div class="cs-add-ai-row"><button id="${BUTTON_ID}" type="button">✦ Fill remaining fields with AI</button><span class="cs-add-ai-help">Enter a title first. Gemini will identify the book and fill the form. Nothing is saved automatically.</span></div><div id="${STATUS_ID}" aria-live="polite"></div>`;const grid=body.querySelector(".form-grid");if(grid)grid.insertBefore(w,grid.children[3]||null);else body.prepend(w);field(BUTTON_ID).addEventListener("click",fillWithAI)}
  function clearMarks(){document.querySelectorAll(".cs-ai-filled").forEach(e=>e.classList.remove("cs-ai-filled"))}
  function schema(){return{type:"object",properties:{author:{type:"string"},year:{type:"integer"},rating:{type:"number"},pages:{type:"integer"},genre:{type:"string"},subgenre:{type:"string"},series:{type:"string"},seriesPos:{type:"number"},honors:{type:"string"},synopsis:{type:"string"},tags:{type:"array",items:{type:"string"}},lit:{type:"integer"},genre_s:{type:"integer"},score:{type:"integer"}},required:["author","year","rating","pages","genre","subgenre","series","honors","synopsis","tags"]}}
  function prompt(title,shelf){const scoring=shelf==="crossover"?"Also give best-effort editable 0–100 lit and genre_s estimates based on real award/critical and genre recognition. Do not claim they are verified.":"Also give a best-effort editable 0–100 score in the app's editorial/consensus style. Do not claim it is verified.";return`Identify this real published book and return ONLY JSON matching the schema. Do not invent titles, authors, years, awards, or other facts. Use standard English publication details. If genuinely unknown, use a conservative value rather than fabricate specificity.\n\nTitle: ${title}\nShelf: ${shelf}\n\nFill author, original publication year, approximate reader-rating consensus (0–5; not live), approximate common-edition pages, concise genre, concise subgenre, series or Standalone, series position when clear, major real awards/recognition, 1–2 spoiler-light synopsis sentences, and 3–6 thematic/style tags.\n${scoring}\nThis is a form-fill assistant only; never save or submit the book.`}
  function parse(t){try{return JSON.parse(t)}catch(_){const m=t.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);if(m){try{return JSON.parse(m[1])}catch(_){}}throw new Error("Gemini returned an unreadable response.")}}
  function validate(d,shelf){if(!d||typeof d!=="object"||!String(d.author||"").trim())throw new Error("Gemini could not determine the author confidently.");const y=Number(d.year),p=Number(d.pages),r=Number(d.rating);if(!Number.isInteger(y)||y<1000||y>new Date().getFullYear()+2)throw new Error("Gemini returned an invalid publication year.");if(!Number.isInteger(p)||p<1||p>10000)throw new Error("Gemini returned an invalid page count.");if(!Number.isFinite(r)||r<0||r>5)throw new Error("Gemini returned an invalid rating.");if(shelf==="crossover"?( !Number.isInteger(Number(d.lit))||!Number.isInteger(Number(d.genre_s))):!Number.isInteger(Number(d.score)))throw new Error("Gemini returned an invalid score.");return d}
  async function fillWithAI(){const title=titleInput()?.value.trim();if(!title){setStatus("Enter the book title first.",true);titleInput()?.focus();return}const s=loadSettings();if(!s.apiKey){setStatus("No Gemini API key is configured. Save your key in AI Recommendations first.",true);return}const b=field(BUTTON_ID);b.disabled=true;b.textContent="✦ Researching book…";setStatus("Gemini is identifying the book. Nothing will be saved automatically.");clearMarks();try{const shelf=field("f-shelf")?.value||"crossover",endpoint=`${API_ROOT}${encodeURIComponent(s.model||DEFAULT_MODEL)}:generateContent`;const res=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":s.apiKey},body:JSON.stringify({contents:[{role:"user",parts:[{text:prompt(title,shelf)}]}],generationConfig:{responseMimeType:"application/json",responseSchema:schema(),temperature:.1}})}),data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data?.error?.message||`Gemini request failed (${res.status}).`);const text=data?.candidates?.[0]?.content?.parts?.map(p=>p.text||"").join("")||"";if(!text)throw new Error("Gemini returned no book details.");const d=validate(parse(text),shelf);setValue("f-author",d.author);setValue("f-year",d.year);setValue("f-rating",Math.round(Number(d.rating)*10)/10);setValue("f-pages",d.pages);setValue("f-genre",d.genre);setValue("f-subgenre",d.subgenre);setValue("f-series",d.series||"Standalone");if(d.seriesPos!==undefined)setValue("f-series-pos",d.seriesPos);setValue("f-honors",d.honors);setValue("f-synopsis",d.synopsis);setValue("f-tags",Array.isArray(d.tags)?d.tags.join(", "):"");if(shelf==="crossover"){setValue("f-lit",clamp(d.lit,0,100));setValue("f-genre-s",clamp(d.genre_s,0,100))}else setValue("f-score",clamp(d.score,0,100));setStatus("AI filled the form. Review every field — especially awards and score — before clicking Save book.")}catch(e){setStatus(e?.message||"AI could not fill the form.",true)}finally{b.disabled=false;b.textContent="✦ Fill remaining fields with AI"}}
  function watch(){ensureUI();document.addEventListener("click",e=>{if(e.target.closest("#addBookBtn"))setTimeout(()=>{clearMarks();ensureUI()},0)},true);const f=field("bookFormModalBackdrop");if(f)new MutationObserver(()=>{if(f.classList.contains("open"))ensureUI()}).observe(f,{attributes:true,attributeFilter:["class"]})}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",watch,{once:true});else watch();
})();
